name: test
on:
  workflow_dispatch:
  push:
    paths:
      - "**.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".github/workflows/test.yml"

jobs:
  tests:
    # TODO: temp until the kAXErrorNoValue problem is fixed
    if: false

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # TODO: add windows-latest when functional
        # NOTE: `macos-13` has SIP disabled, which allows us to enable accessibility permissions.
        os: [macos-13]

    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      # TODO: for some reason all the tests return kAXErrorNoValue only on github action runners
      - name: cargo test
        # TODO: macos requires this to run on main thread, is this scalable?
        run: cargo test --all-features --all-targets -- --test-threads 1
